name: flake8

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.py"

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repo
        uses: actions/checkout@v2

      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: flake8-lint
        uses: py-actions/flake8@v2
