name: "Testing"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python all python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64

      - name: Install dependencies
        run: |
          python -m venv --upgrade-deps .venv
          source .venv/bin/activate
          pip install .[all]

      - name: Run Test
        run: |
          source .venv/bin/activate
          python -m pytest .
